services:
  api:
    build:
      context: .
    environment:
      DBHOST: db
      DBUSER: gocatgo
      DBPASSWORD: gocatgo
      DBNAME: gocatgo
      DBPORT: 3306
    links:
      - db
    ports:
      - 8080:8080
    restart: always
    networks:
      - gocatgo
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:9.2.0
    environment:
      MYSQL_DATABASE: gocatgo
      MYSQL_ROOT_PASSWORD: gocatgoadmin
      MYSQL_USER: gocatgo
      MYSQL_PASSWORD: gocatgo
    ports:
      - 3306:3306
    restart: always
    networks:
      - gocatgo
    # volumes:
    #   - ./data/postgresql/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 0s

networks:
  gocatgo:
    name: gocatgo

