version: '3.8'

services:
  api:
    build:
      context: .
    environment:
      DBHOST: db
      DBUSER: gocatgo
      DBPASSWORD: gocatgo
      DBNAME: gocatgo
      DBPORT: 5432
    links:
      - db
    ports:
      - 8080:8080
    restart: always
    networks:
      - gocatgo
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: gocatgo
      POSTGRES_USER: gocatgo
      POSTGRES_PASSWORD: gocatgo
    ports:
      - 5432:5432
    restart: always
    networks:
      - gocatgo
    volumes:
      - /data/postgresql/:/var/lib/postgresql/data
    healthcheck:
      test: "exit 0"

networks:
  gocatgo:
    name: gocatgo

